/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Pelin
 */

public class MusteriSecenek extends javax.swing.JFrame {
 Color custom=new Color(204,204,204);
 Color fontcolor=new Color(51,51,51);
 Color changefont=Color.DARK_GRAY;
 Color exitcolor=new Color(255,153,0);
 Font newfont=new Font("Segoe UI ", Font.BOLD, 19);
 Font oldfont=new Font("Segoe UI ", Font.PLAIN, 18);
 int musteri_id;/**
     * Creates new form MusteriSecenek1
     */ 

    public MusteriSecenek() {
        
         
       // initComponents();
        
        
    }
    public MusteriSecenek(int musteri_id){
        this.musteri_id=musteri_id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        anaPanel = new javax.swing.JPanel();
        hesabaTransfer = new java.awt.Panel();
        jLabel8 = new javax.swing.JLabel();
        yeniHesap = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        hesapSil = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        bilgiGuncelle = new java.awt.Panel();
        jLabel11 = new javax.swing.JLabel();
        bankayaTransfer = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        krediTalebi = new java.awt.Panel();
        jLabel13 = new javax.swing.JLabel();
        aylikOzet = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        hesaptancek = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hesabaYatır = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(423, 130));
        setUndecorated(true);

        anaPanel.setBackground(new java.awt.Color(204, 204, 204));
        anaPanel.setPreferredSize(new java.awt.Dimension(905, 650));

        hesabaTransfer.setBackground(new java.awt.Color(204, 204, 204));
        hesabaTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hesabaTransfer.setPreferredSize(new java.awt.Dimension(905, 65));
        hesabaTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hesabaTransferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hesabaTransferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hesabaTransferMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel8.setText(" Başka Bir Hesaba Para Transferi");

        javax.swing.GroupLayout hesabaTransferLayout = new javax.swing.GroupLayout(hesabaTransfer);
        hesabaTransfer.setLayout(hesabaTransferLayout);
        hesabaTransferLayout.setHorizontalGroup(
            hesabaTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesabaTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        hesabaTransferLayout.setVerticalGroup(
            hesabaTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesabaTransferLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        yeniHesap.setBackground(new java.awt.Color(204, 204, 204));
        yeniHesap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        yeniHesap.setPreferredSize(new java.awt.Dimension(905, 65));
        yeniHesap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yeniHesapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yeniHesapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yeniHesapMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel9.setText(" Yeni Hesap Açma Talebi");

        javax.swing.GroupLayout yeniHesapLayout = new javax.swing.GroupLayout(yeniHesap);
        yeniHesap.setLayout(yeniHesapLayout);
        yeniHesapLayout.setHorizontalGroup(
            yeniHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniHesapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        yeniHesapLayout.setVerticalGroup(
            yeniHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yeniHesapLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        hesapSil.setBackground(new java.awt.Color(204, 204, 204));
        hesapSil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hesapSil.setPreferredSize(new java.awt.Dimension(905, 65));
        hesapSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hesapSilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hesapSilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hesapSilMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel10.setText(" Hesap Silme Talebi ");

        javax.swing.GroupLayout hesapSilLayout = new javax.swing.GroupLayout(hesapSil);
        hesapSil.setLayout(hesapSilLayout);
        hesapSilLayout.setHorizontalGroup(
            hesapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesapSilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hesapSilLayout.setVerticalGroup(
            hesapSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesapSilLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bilgiGuncelle.setBackground(new java.awt.Color(204, 204, 204));
        bilgiGuncelle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bilgiGuncelle.setPreferredSize(new java.awt.Dimension(905, 65));
        bilgiGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bilgiGuncelleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilgiGuncelleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilgiGuncelleMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel11.setText(" Bilgileri Güncelle");

        javax.swing.GroupLayout bilgiGuncelleLayout = new javax.swing.GroupLayout(bilgiGuncelle);
        bilgiGuncelle.setLayout(bilgiGuncelleLayout);
        bilgiGuncelleLayout.setHorizontalGroup(
            bilgiGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilgiGuncelleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bilgiGuncelleLayout.setVerticalGroup(
            bilgiGuncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilgiGuncelleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bankayaTransfer.setBackground(new java.awt.Color(204, 204, 204));
        bankayaTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bankayaTransfer.setPreferredSize(new java.awt.Dimension(905, 65));
        bankayaTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bankayaTransferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bankayaTransferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bankayaTransferMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel12.setText(" Bankaya Para Transferi");

        javax.swing.GroupLayout bankayaTransferLayout = new javax.swing.GroupLayout(bankayaTransfer);
        bankayaTransfer.setLayout(bankayaTransferLayout);
        bankayaTransferLayout.setHorizontalGroup(
            bankayaTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankayaTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bankayaTransferLayout.setVerticalGroup(
            bankayaTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankayaTransferLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        krediTalebi.setBackground(new java.awt.Color(204, 204, 204));
        krediTalebi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        krediTalebi.setPreferredSize(new java.awt.Dimension(905, 65));
        krediTalebi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                krediTalebiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                krediTalebiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                krediTalebiMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel13.setText(" Kredi Talebi");

        javax.swing.GroupLayout krediTalebiLayout = new javax.swing.GroupLayout(krediTalebi);
        krediTalebi.setLayout(krediTalebiLayout);
        krediTalebiLayout.setHorizontalGroup(
            krediTalebiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krediTalebiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        krediTalebiLayout.setVerticalGroup(
            krediTalebiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krediTalebiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        aylikOzet.setBackground(new java.awt.Color(204, 204, 204));
        aylikOzet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aylikOzet.setPreferredSize(new java.awt.Dimension(905, 65));
        aylikOzet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aylikOzetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aylikOzetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aylikOzetMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel14.setText(" Aylık Özet Görüntüle");
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout aylikOzetLayout = new javax.swing.GroupLayout(aylikOzet);
        aylikOzet.setLayout(aylikOzetLayout);
        aylikOzetLayout.setHorizontalGroup(
            aylikOzetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aylikOzetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aylikOzetLayout.setVerticalGroup(
            aylikOzetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aylikOzetLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        hesaptancek.setBackground(new java.awt.Color(204, 204, 204));
        hesaptancek.setPreferredSize(new java.awt.Dimension(905, 65));
        hesaptancek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hesaptancekMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hesaptancekMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hesaptancekMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel2.setText("  Hesaptan Para Çek");

        javax.swing.GroupLayout hesaptancekLayout = new javax.swing.GroupLayout(hesaptancek);
        hesaptancek.setLayout(hesaptancekLayout);
        hesaptancekLayout.setHorizontalGroup(
            hesaptancekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesaptancekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(686, Short.MAX_VALUE))
        );
        hesaptancekLayout.setVerticalGroup(
            hesaptancekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesaptancekLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        hesabaYatır.setBackground(new java.awt.Color(204, 204, 204));
        hesabaYatır.setPreferredSize(new java.awt.Dimension(905, 65));
        hesabaYatır.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hesabaYatırMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hesabaYatırMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hesabaYatırMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/images/right-arrow.png"))); // NOI18N
        jLabel1.setText("  Hesaba Para Yatır");

        javax.swing.GroupLayout hesabaYatırLayout = new javax.swing.GroupLayout(hesabaYatır);
        hesabaYatır.setLayout(hesabaYatırLayout);
        hesabaYatırLayout.setHorizontalGroup(
            hesabaYatırLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesabaYatırLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hesabaYatırLayout.setVerticalGroup(
            hesabaYatırLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesabaYatırLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        exit.setBackground(new java.awt.Color(51, 51, 255));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 153, 0));
        exit.setText("X");
        exit.setToolTipText("");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout anaPanelLayout = new javax.swing.GroupLayout(anaPanel);
        anaPanel.setLayout(anaPanelLayout);
        anaPanelLayout.setHorizontalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hesabaTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hesapSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(krediTalebi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bankayaTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bilgiGuncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aylikOzet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(yeniHesap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hesaptancek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hesabaYatır, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anaPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        anaPanelLayout.setVerticalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaPanelLayout.createSequentialGroup()
                .addComponent(exit)
                .addGap(2, 2, 2)
                .addComponent(hesabaYatır, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(hesaptancek, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(yeniHesap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(hesapSil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(hesabaTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bilgiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bankayaTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(krediTalebi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(aylikOzet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yeniHesapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yeniHesapMouseClicked
        dispose(); 
        new musteriHesapEkle(this.musteri_id).setVisible(true);
          
           
       // TODO add your handling code here:
    }//GEN-LAST:event_yeniHesapMouseClicked

    private void aylikOzetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aylikOzetMouseClicked
       dispose();  
        new musteriAylikOzet(this.musteri_id).setVisible(true);               
// TODO add your handling code here:
    }//GEN-LAST:event_aylikOzetMouseClicked

    private void hesabaTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesabaTransferMouseClicked
        dispose();       
        new musteriHesabaTransfer(this.musteri_id).setVisible(true);
           
    }//GEN-LAST:event_hesabaTransferMouseClicked

    private void bilgiGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilgiGuncelleMouseClicked
        dispose();    
        new musteriBilgiGuncelle(this.musteri_id).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_bilgiGuncelleMouseClicked

    private void bankayaTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankayaTransferMouseClicked
        dispose();  
        new musteriBankaTransfer(this.musteri_id).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_bankayaTransferMouseClicked

    private void krediTalebiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_krediTalebiMouseClicked
        dispose();   
        new musteriKrediTalep(this.musteri_id).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_krediTalebiMouseClicked

    private void hesapSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesapSilMouseClicked
        dispose();  
        new musteriHesapSil(this.musteri_id).setVisible(true);
    
		
    }//GEN-LAST:event_hesapSilMouseClicked
    
    private void hesabaYatırMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesabaYatırMouseClicked
       dispose(); 
        new musteriParaYatir(this.musteri_id).setVisible(true);
    }//GEN-LAST:event_hesabaYatırMouseClicked

    private void hesaptancekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesaptancekMouseClicked
       dispose(); 
        new musteriParaCek(this.musteri_id).setVisible(true);
    }//GEN-LAST:event_hesaptancekMouseClicked

    private void hesabaYatırMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesabaYatırMouseEntered
       this.hesabaYatır.setBackground(Color.LIGHT_GRAY);
       this.jLabel1.setForeground(changefont);
       this.jLabel1.setFont(newfont);
    }//GEN-LAST:event_hesabaYatırMouseEntered

    private void hesabaYatırMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesabaYatırMouseExited
      this.hesabaYatır.setBackground(custom);
       this.jLabel1.setForeground(fontcolor);
       this.jLabel1.setFont(oldfont);
       
    }//GEN-LAST:event_hesabaYatırMouseExited

    private void hesaptancekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesaptancekMouseEntered
       this.hesaptancek.setBackground(Color.LIGHT_GRAY);
       this.jLabel2.setForeground(changefont);
       this.jLabel2.setFont(newfont);
    }//GEN-LAST:event_hesaptancekMouseEntered

    private void hesaptancekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesaptancekMouseExited
         this.hesaptancek.setBackground(custom);
       this.jLabel2.setForeground(fontcolor);
       this.jLabel2.setFont(oldfont);
    }//GEN-LAST:event_hesaptancekMouseExited

    private void hesabaTransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesabaTransferMouseEntered
         this.hesabaTransfer.setBackground(Color.LIGHT_GRAY);
       this.jLabel8.setForeground(changefont);
       this.jLabel8.setFont(newfont);
    }//GEN-LAST:event_hesabaTransferMouseEntered

    private void hesabaTransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesabaTransferMouseExited
       this.hesabaTransfer.setBackground(custom);
       this.jLabel8.setForeground(fontcolor);
       this.jLabel8.setFont(oldfont);
    }//GEN-LAST:event_hesabaTransferMouseExited

    private void yeniHesapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yeniHesapMouseEntered
       this.yeniHesap.setBackground(Color.LIGHT_GRAY);
       this.jLabel9.setForeground(changefont);
       this.jLabel9.setFont(newfont);
    }//GEN-LAST:event_yeniHesapMouseEntered

    private void yeniHesapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yeniHesapMouseExited
         this.yeniHesap.setBackground(custom);
       this.jLabel9.setForeground(fontcolor);
       this.jLabel9.setFont(oldfont);
    }//GEN-LAST:event_yeniHesapMouseExited

    private void hesapSilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesapSilMouseEntered
        this.hesapSil.setBackground(Color.LIGHT_GRAY);
       this.jLabel10.setForeground(changefont);
       this.jLabel10.setFont(newfont);
    }//GEN-LAST:event_hesapSilMouseEntered

    private void hesapSilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesapSilMouseExited
        this.hesapSil.setBackground(custom);
       this.jLabel10.setForeground(fontcolor);
       this.jLabel10.setFont(oldfont);
    }//GEN-LAST:event_hesapSilMouseExited

    private void bilgiGuncelleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilgiGuncelleMouseEntered
       this.bilgiGuncelle.setBackground(Color.LIGHT_GRAY);
       this.jLabel11.setForeground(changefont);
       this.jLabel11.setFont(newfont);
    }//GEN-LAST:event_bilgiGuncelleMouseEntered

    private void bilgiGuncelleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilgiGuncelleMouseExited
       this.bilgiGuncelle.setBackground(custom);
       this.jLabel11.setForeground(fontcolor);
       this.jLabel11.setFont(oldfont);
    }//GEN-LAST:event_bilgiGuncelleMouseExited

    private void bankayaTransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankayaTransferMouseEntered
       this.bankayaTransfer.setBackground(Color.LIGHT_GRAY);
       this.jLabel12.setForeground(changefont);
       this.jLabel12.setFont(newfont);
    }//GEN-LAST:event_bankayaTransferMouseEntered

    private void bankayaTransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankayaTransferMouseExited
        this.bankayaTransfer.setBackground(custom);
       this.jLabel12.setForeground(fontcolor);
       this.jLabel12.setFont(oldfont);
    }//GEN-LAST:event_bankayaTransferMouseExited

    private void krediTalebiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_krediTalebiMouseExited
         this.krediTalebi.setBackground(custom);
       this.jLabel13.setForeground(fontcolor);
       this.jLabel13.setFont(oldfont);
    }//GEN-LAST:event_krediTalebiMouseExited

    private void krediTalebiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_krediTalebiMouseEntered
        this.krediTalebi.setBackground(Color.LIGHT_GRAY);
       this.jLabel13.setForeground(changefont);
       this.jLabel13.setFont(newfont);
    }//GEN-LAST:event_krediTalebiMouseEntered

    private void aylikOzetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aylikOzetMouseEntered
       this.aylikOzet.setBackground(Color.LIGHT_GRAY);
       this.jLabel14.setForeground(changefont);
       this.jLabel14.setFont(newfont);
    }//GEN-LAST:event_aylikOzetMouseEntered

    private void aylikOzetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aylikOzetMouseExited
        this.aylikOzet.setBackground(custom);
       this.jLabel14.setForeground(fontcolor);
       this.jLabel14.setFont(oldfont);
    }//GEN-LAST:event_aylikOzetMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
      dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered

       this.exit.setForeground(Color.getHSBColor(54, 54, 54));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        this.exit.setForeground(exitcolor);
    }//GEN-LAST:event_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriSecenek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriSecenek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriSecenek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriSecenek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriSecenek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anaPanel;
    private java.awt.Panel aylikOzet;
    private java.awt.Panel bankayaTransfer;
    private java.awt.Panel bilgiGuncelle;
    private javax.swing.JLabel exit;
    private java.awt.Panel hesabaTransfer;
    private javax.swing.JPanel hesabaYatır;
    private java.awt.Panel hesapSil;
    private javax.swing.JPanel hesaptancek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Panel krediTalebi;
    private java.awt.Panel yeniHesap;
    // End of variables declaration//GEN-END:variables
}
