/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;


import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Locale;
import javaapplication1.TemsilciSecenek;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pelin
 */
public class musteriAylikOzet extends javax.swing.JFrame {
     int musteri_id;
     DefaultTableModel tblModel;
    /**
     * Creates new form musteriAylikOzet
     */
    public musteriAylikOzet() {
       // initComponents();
    }
    public musteriAylikOzet(int musteri_id){
        this.musteri_id=musteri_id;
        initComponents();
        
        this.tblModel=(DefaultTableModel)tableModel.getModel();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guncelpanel = new javax.swing.JPanel();
        geneldurumtable = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        goster = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kapat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(423, 130));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(905, 650));

        guncelpanel.setPreferredSize(new java.awt.Dimension(640, 380));

        tableModel.setAutoCreateRowSorter(true);
        tableModel.setBackground(new java.awt.Color(228, 228, 250));
        tableModel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İşlem Ad", "Kaynak Hesap", "Hedef Hesap", "Tutar", "Kaynak Bakiye", "Hedef Bakiye", "Tarih", "Hesap ID "
            }
        ));
        tableModel.setRowHeight(40);
        geneldurumtable.setViewportView(tableModel);

        goster.setBackground(new java.awt.Color(255, 204, 153));
        goster.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        goster.setForeground(new java.awt.Color(255, 255, 255));
        goster.setText("Göster");
        goster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gosterMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("Müşteri Aylık Özet Görüntüle ");

        kapat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kapat.setForeground(new java.awt.Color(255, 153, 102));
        kapat.setText("X");
        kapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout guncelpanelLayout = new javax.swing.GroupLayout(guncelpanel);
        guncelpanel.setLayout(guncelpanelLayout);
        guncelpanelLayout.setHorizontalGroup(
            guncelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guncelpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guncelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guncelpanelLayout.createSequentialGroup()
                        .addComponent(geneldurumtable, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guncelpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guncelpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goster, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(guncelpanelLayout.createSequentialGroup()
                .addGap(744, 744, 744)
                .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guncelpanelLayout.setVerticalGroup(
            guncelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guncelpanelLayout.createSequentialGroup()
                .addComponent(kapat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(geneldurumtable, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(goster, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guncelpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guncelpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gosterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gosterMouseClicked

        Calendar cal = Calendar.getInstance(Locale.getDefault());
        int month = cal.get(Calendar.MONTH)+1 ;
     
        System.out.print(month);
        try {
            System.out.println(month);
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
            PreparedStatement st = (PreparedStatement) connection
            .prepareStatement("Select *from islemler i inner join  hesaplar h ON i.HesapId=h.HesapId where h.MusteriId=? and month(i.Tarih)=?");
            st.setInt(1, this.musteri_id);
            st.setInt(2,month);
            ResultSet rs2 = st.executeQuery();
            while (rs2.next()) {
                String kaynakhesap=rs2.getString("KaynakHesap");
                String hedefhesap=rs2.getString("HedefHesap");
                String islemad=rs2.getString("IslemAd");
                int tutar=rs2.getInt("Tutar");
                int kaynakbakiye=rs2.getInt("KaynakBakiye");
                int hedefbakiye=rs2.getInt("HedefBakiye");
                Date tarih=rs2.getDate("Tarih");
                int hesapid=rs2.getInt("HesapId");

                String data[]={String.valueOf(islemad),String.valueOf(kaynakhesap),String.valueOf(hedefhesap),
                    String.valueOf(tutar),String.valueOf(kaynakbakiye),String.valueOf(hedefbakiye),String.valueOf(tarih),String.valueOf(hesapid)};
                DefaultTableModel tblModel=(DefaultTableModel)tableModel.getModel();
                tblModel.addRow(data);

            }
            connection.close();
            
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
    }//GEN-LAST:event_gosterMouseClicked

    private void kapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseClicked
        dispose();
        new MusteriSecenek(this.musteri_id).setVisible(true);
    }//GEN-LAST:event_kapatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriAylikOzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriAylikOzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriAylikOzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriAylikOzet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriAylikOzet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane geneldurumtable;
    private javax.swing.JButton goster;
    private javax.swing.JPanel guncelpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kapat;
    private javax.swing.JTable tableModel;
    // End of variables declaration//GEN-END:variables
}
