/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Pelin
 */
public class musteriHesapSil extends javax.swing.JFrame {
    int musteri_id;
    /**
     * Creates new form musteriHesapSil
     */
    public musteriHesapSil() {
        initComponents();
    }
     public musteriHesapSil(int musteri_id) {
         this.musteri_id=musteri_id;
        initComponents();
         try {
		  Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
          PreparedStatement st = (PreparedStatement) connection
              .prepareStatement("Select *from hesaplar where MusteriId = ? and HesapOnay=1");
          st.setInt(1, musteri_id);
          ResultSet rs = st.executeQuery();
          while (rs.next()) {
          	String hesaplar = rs.getString("HesapAd");
          	silinen_hesap.addItem(hesaplar);
          }
      } catch (SQLException sqlException) {
          sqlException.printStackTrace();
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        silPanel = new javax.swing.JPanel();
        label10 = new java.awt.Label();
        silBtn = new javax.swing.JToggleButton();
        iptalBtn = new javax.swing.JToggleButton();
        silinen_hesap = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(423, 130));
        setUndecorated(true);

        silPanel.setPreferredSize(new java.awt.Dimension(640, 380));

        label10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label10.setText("Silinecek Hesap   :");

        silBtn.setBackground(new java.awt.Color(0, 0, 51));
        silBtn.setForeground(new java.awt.Color(204, 204, 204));
        silBtn.setText("SİL");
        silBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                silBtnMouseClicked(evt);
            }
        });

        iptalBtn.setBackground(new java.awt.Color(51, 0, 0));
        iptalBtn.setForeground(new java.awt.Color(204, 204, 204));
        iptalBtn.setText("İPTAL");
        iptalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iptalBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout silPanelLayout = new javax.swing.GroupLayout(silPanel);
        silPanel.setLayout(silPanelLayout);
        silPanelLayout.setHorizontalGroup(
            silPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, silPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(silPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iptalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(silPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(silBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silinen_hesap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );
        silPanelLayout.setVerticalGroup(
            silPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(silPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(silPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silinen_hesap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(silPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iptalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(silPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(silPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void silBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_silBtnMouseClicked

        try
        {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
            PreparedStatement st = connection.prepareStatement("Select * from hesaplar where HesapAd = ? and MusteriId=?");
            st.setString(1, String.valueOf(silinen_hesap.getSelectedItem()));
            st.setInt(2, musteri_id);
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                double bakiye = rs.getDouble("Bakiye");
                int hesapid=rs.getInt("HesapId");
                if(bakiye==0) {
                     PreparedStatement st3 = connection.prepareStatement("delete k.* from kredi_talep  k inner join hesaplar h ON  k.HesapId=h.HesapId where h. HesapId = ?");
                    st3.setInt(1, hesapid);
                    st3.execute();
                    
                    PreparedStatement st4 = connection.prepareStatement("delete g.* from geneldurum g inner join hesaplar  h  ON g.HesapId=h.HesapId  where h. HesapId = ?  ");
                    st4.setInt(1, hesapid);
                    st4.execute();
                    
                    
                    
                    
                    PreparedStatement st2 = connection.prepareStatement("delete h from hesaplar h where h. HesapId = ? and h.MusteriId=?");
                    st2.setInt(1, hesapid);
                    st2.setInt(2, musteri_id);
                    st2.execute();
                    JOptionPane.showMessageDialog(null, "Hesap Silindi");
                }

                else {
                    JOptionPane.showMessageDialog(null, "Bakiyeniz oldugu için hesap silinemedi");
                }

                connection.close();
                dispose();
                new musteriHesapSil(this.musteri_id).setVisible(true);
               
            }

        }
        catch (SQLException  ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_silBtnMouseClicked

    private void iptalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iptalBtnMouseClicked
       dispose();
        new MusteriSecenek(this.musteri_id).setVisible(true);
    }//GEN-LAST:event_iptalBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriHesapSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriHesapSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriHesapSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriHesapSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriHesapSil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton iptalBtn;
    private java.awt.Label label10;
    private javax.swing.JToggleButton silBtn;
    private javax.swing.JPanel silPanel;
    private javax.swing.JComboBox<String> silinen_hesap;
    // End of variables declaration//GEN-END:variables
}
