/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1.temsilci;
import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Locale;
import javaapplication1.TemsilciSecenek;
import javax.swing.JOptionPane;
/**
 *
 * @author Pelin
 */
public class Talepler extends javax.swing.JFrame {
   int temsilci_id;
   boolean hesap_onaylandi_mi=false;
    /**
     * Creates new form Talepler
     */
    public Talepler() {
       // initComponents();
    }
    public Talepler(int temsilci_id) {
        this.temsilci_id=temsilci_id;
        initComponents();
         try {
		 Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
	          PreparedStatement st = (PreparedStatement) connection
                        //  Select distinct AdSoyad from musteriler m inner join hesaplar h ON m.MusteriId=h.MusteriId where m.TemsilciId=? and h.MusteriId in(Select distinct MusteriId from hesaplar h inner join kredi_talep k  ON h.HesapId=k.HesapId) and HesapOnay=1"
	              .prepareStatement("Select distinct m.MusteriId from musteriler m inner join hesaplar h ON m.MusteriId=h.MusteriId where m.TemsilciId=? and h.HesapOnay=0 ");
                     st.setInt(1,this.temsilci_id);
	          ResultSet rs = st.executeQuery();
	          while (rs.next()) {
	          	//String hesaplar = rs.getString("HesapAd");
	          	int musteri_id = rs.getInt("MusteriId");
	         
	          	 PreparedStatement st2 = (PreparedStatement) connection
			              .prepareStatement("Select *from musteriler where MusteriId = ?");
	          	 	  st2.setString(1, String.valueOf(musteri_id));
			          ResultSet rs2 = st2.executeQuery();
			          while (rs2.next()) {
			          	String adsoyad = rs2.getString("AdSoyad");
			          	ad.addItem(adsoyad);
			          
			        
			          }
			         
	          } connection.close();
	         
	      } catch (SQLException sqlException) {
	          sqlException.printStackTrace();
	      }
             

                try {
			  Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
	          PreparedStatement st = (PreparedStatement) connection
	              .prepareStatement("Select distinct AdSoyad from musteriler m inner join hesaplar h ON m.MusteriId=h.MusteriId where m.TemsilciId=? and h.MusteriId in(Select distinct MusteriId from hesaplar h inner join kredi_talep k  ON h.HesapId=k.HesapId) and h.HesapOnay=1");
	          st.setInt(1, this.temsilci_id);
	          ResultSet rs = st.executeQuery();
	          while (rs.next()) {
	          	String ad= rs.getString("Adsoyad");
	          	ad2.addItem(ad);
	          	
			         
	          } connection.close();
	         
	      } catch (SQLException sqlException) {
	          sqlException.printStackTrace();
	      }
		try {
			
		 Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
	          PreparedStatement st = (PreparedStatement) connection
		              .prepareStatement("select *from kredi_talep k inner join hesaplar h ON h.HesapId=k.HesapId where k.KrediOnay=0 and h.HesapId in(select HesapId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=? and h.HesapAd=?)");
	          st.setString(1, String.valueOf(ad2.getSelectedItem()));
	          st.setString(2, String.valueOf(hesapad2.getSelectedItem()));
	          ResultSet rs = st.executeQuery();
	          while (rs.next()) {
	          	Double tutar= rs.getDouble("Tutar");
	           	int vade= rs.getInt("Vade");
	          	lblvade.setText(String.valueOf(vade));
	          	lbltutar.setText(String.valueOf(tutar));
	          	
			         
	          } connection.close();
	         
	      } catch (SQLException sqlException) {
	          sqlException.printStackTrace();
	      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        talepler = new javax.swing.JPanel();
        iptal = new javax.swing.JToggleButton();
        hesapOnay = new javax.swing.JToggleButton();
        ad = new javax.swing.JComboBox<>();
        hesapad = new javax.swing.JComboBox<>();
        ad2 = new javax.swing.JComboBox<>();
        hesapad2 = new javax.swing.JComboBox<>();
        kredionay = new javax.swing.JToggleButton();
        lblvade = new java.awt.Label();
        lbltutar = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(423, 130));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(905, 650));

        talepler.setPreferredSize(new java.awt.Dimension(640, 380));

        iptal.setForeground(new java.awt.Color(204, 0, 0));
        iptal.setText("İPTAL");
        iptal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iptal(evt);
            }
        });

        hesapOnay.setBackground(new java.awt.Color(255, 153, 102));
        hesapOnay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hesapOnay.setForeground(new java.awt.Color(255, 255, 255));
        hesapOnay.setText("HESAP ONAYLA");
        hesapOnay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hesapOnayMouseClicked(evt);
            }
        });

        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        hesapad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapadActionPerformed(evt);
            }
        });

        ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad2ActionPerformed(evt);
            }
        });

        hesapad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapad2ActionPerformed(evt);
            }
        });

        kredionay.setBackground(new java.awt.Color(255, 153, 102));
        kredionay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kredionay.setForeground(new java.awt.Color(255, 255, 255));
        kredionay.setText("KREDİ ONAYLA");
        kredionay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kredionayMouseClicked(evt);
            }
        });

        lblvade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbltutar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("VADE:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("TUTAR :");

        javax.swing.GroupLayout taleplerLayout = new javax.swing.GroupLayout(talepler);
        talepler.setLayout(taleplerLayout);
        taleplerLayout.setHorizontalGroup(
            taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taleplerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taleplerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvade, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hesapad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(taleplerLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbltutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(hesapad2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hesapOnay, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(kredionay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(iptal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        taleplerLayout.setVerticalGroup(
            taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taleplerLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hesapad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hesapOnay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kredionay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hesapad2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iptal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(taleplerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(lblvade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(talepler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(talepler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iptal(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iptal
        dispose();
        new TemsilciSecenek(this.temsilci_id).setVisible(true);
    }//GEN-LAST:event_iptal

    private void hesapOnayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hesapOnayMouseClicked
      
        
        
        try {
					  Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			          PreparedStatement st = (PreparedStatement) connection
			              .prepareStatement("Select *from musteriler where AdSoyad = ?");
			          st.setString(1,String.valueOf( ad.getSelectedItem()));
			          ResultSet rs = st.executeQuery();
			          while (rs.next()) {
			          	int musteri_id = rs.getInt("MusteriId");
			          	try {
				            String query = "update hesaplar set HesapOnay = 1 where MusteriId  = ? and HesapAd=?";
				            PreparedStatement preparedStmt = connection.prepareStatement(query);
				            preparedStmt.setString(1,String.valueOf(musteri_id));
				            preparedStmt.setString(2,String.valueOf(hesapad.getSelectedItem()));
			
				            preparedStmt.executeUpdate();
			               
				       
				        } catch (Exception exception) {
				            exception.printStackTrace();
				        }
						
			          }
                                   connection.close();
                                        hesap_onaylandi_mi=true;
                                        GenelDurumFunc(hesap_onaylandi_mi);
 
			             
			      } catch (SQLException sqlException) {
			          sqlException.printStackTrace();
			      }
        
        
        
        
        
        
        
        
        

                    
					
    }//GEN-LAST:event_hesapOnayMouseClicked

    private void kredionayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kredionayMouseClicked
    Double faiz=0.0;
    int hesapid=0;
     
    Calendar cal = Calendar.getInstance(Locale.getDefault());
    int month = cal.get(Calendar.MONTH)+1 ;
    LocalDate tarih = LocalDate.now(); 
                            try {
					Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			         
		            String query = "update kredi_talep set kredi_talep.Tarih=?,kredi_talep.KrediOnay=1 where kredi_talep.HesapId=(select HesapId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=? and h.HesapAd=?)";
		            PreparedStatement preparedStmt = connection.prepareStatement(query);
		            preparedStmt.setString(1, String.valueOf(tarih));
		            preparedStmt.setString(2, String.valueOf(ad2.getSelectedItem()));
		            preparedStmt.setString(2, String.valueOf(ad2.getSelectedItem()));
		            preparedStmt.setString(3, String.valueOf(hesapad2.getSelectedItem()));
		
		            preparedStmt.executeUpdate();
	               
	               

		        } catch (Exception exception) {
		            exception.printStackTrace();
		        }
                        
                         try {
					
				 Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			          PreparedStatement st = (PreparedStatement) connection
			              .prepareStatement("select *from hesaplar h inner join kredi_talep k ON h.HesapId=k.HesapId where k.KrediOnay=1 and h.HesapId in(select HesapId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=? and h.HesapAd=? )");
			          st.setString(1, String.valueOf(ad2.getSelectedItem()));
			          st.setString(2, String.valueOf(hesapad2.getSelectedItem()));
			          ResultSet rs = st.executeQuery();
			          while (rs.next()) {
			    Double bakiye= rs.getDouble("Bakiye");
                            String query = "update hesaplar set hesaplar.Bakiye=? where hesaplar.HesapAd=? and hesaplar.MusteriId=(select MusteriId from musteriler where AdSoyad=?)";
		            PreparedStatement preparedStmt = connection.prepareStatement(query);
		            preparedStmt.setDouble(1, Double.parseDouble(lbltutar.getText())+bakiye);
		            preparedStmt.setString(2, String.valueOf(hesapad2.getSelectedItem()));
                            preparedStmt.setString(3, String.valueOf(ad2.getSelectedItem()));
                        
		            preparedStmt.executeUpdate();
                            
	                    
                            
                            
			          	
					         
			          } 
			         JOptionPane.showMessageDialog(null, "Onaylandi");
			      } catch (SQLException sqlException) {
			          sqlException.printStackTrace();
			      }
                         
                         
                         try {
					
				 Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			          PreparedStatement st = (PreparedStatement) connection
			              .prepareStatement("select *from hesaplar h inner join kredi_talep k ON h.HesapId=k.HesapId where k.KrediOnay=1 and h.HesapId in(select HesapId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=? and h.HesapAd=? )");
			          st.setString(1, String.valueOf(ad2.getSelectedItem()));
			          st.setString(2, String.valueOf(hesapad2.getSelectedItem()));
			          ResultSet rs = st.executeQuery();
			          while (rs.next()) {
			          hesapid= rs.getInt("HesapId");
                                  }
                             PreparedStatement st2 = (PreparedStatement) connection
			       .prepareStatement("select *from faiz");
			       ResultSet rs2 = st2.executeQuery();
			         if(rs2.next()){
                                faiz=rs2.getDouble("FaizMiktar");
                            }
                            String query = "INSERT INTO borclar (AylikBorc,ToplamBorc,HesapId,Tarih) values('" +((Double.parseDouble(lbltutar.getText())+((Double.parseDouble(lbltutar.getText())*faiz)/100))/Double.parseDouble(lblvade.getText()))+"','" +(Double.parseDouble(lbltutar.getText())+((Double.parseDouble(lbltutar.getText())*faiz)/100))+"','"+hesapid+"','"+tarih+"')";
		            PreparedStatement preparedStmt = connection.prepareStatement(query);
		            preparedStmt.executeUpdate();
                            
         
			         
			         connection.close();
			      } catch (SQLException sqlException) {
			          sqlException.printStackTrace();
			      }
















                                
                                
                               
				
    }//GEN-LAST:event_kredionayMouseClicked

    private void ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad2ActionPerformed
          hesapad2.removeAllItems();
				try {
					
					  Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			          PreparedStatement st = (PreparedStatement) connection
			              .prepareStatement("Select HesapAd from hesaplar h inner join kredi_talep k  ON h.HesapId=k.HesapId where k.KrediOnay=0 and h.MusteriId in(select distinct h.MusteriId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=?) and h.HesapOnay=1");
			          st.setString(1, String.valueOf(hesapad2.getSelectedItem()));
			          ResultSet rs = st.executeQuery();
			          while (rs.next()) {
			          	String hesapAd= rs.getString("HesapAd");
			          	hesapad2.addItem(hesapAd);
			          	
			          } connection.close();
			         
			      } catch (SQLException sqlException) {
			          sqlException.printStackTrace();
			      }
					
        try {
					
					  Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			          PreparedStatement st = (PreparedStatement) connection
			              .prepareStatement("Select HesapAd from hesaplar h inner join kredi_talep k  ON h.HesapId=k.HesapId where k.KrediOnay=0 and h.MusteriId in(select distinct h.MusteriId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=?)");
			          st.setString(1, String.valueOf(ad2.getSelectedItem()));
			          ResultSet rs = st.executeQuery();
			          while (rs.next()) {
			          	String hesapAd= rs.getString("HesapAd");
			          	hesapad2.addItem(hesapAd);
			          	
			          } connection.close();
			         
			      } catch (SQLException sqlException) {
			          sqlException.printStackTrace();
			      }
                
                
                
           
		try {
			
			  Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
	          PreparedStatement st = (PreparedStatement) connection
		              .prepareStatement("select *from kredi_talep k inner join hesaplar h ON h.HesapId=k.HesapId where k.KrediOnay=0 and h.HesapId in(select HesapId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=? and h.HesapAd=?)");
	          st.setString(1, String.valueOf(ad2.getSelectedItem()));
	          st.setString(2, String.valueOf(hesapad2.getSelectedItem()));
	          ResultSet rs = st.executeQuery();
	          while (rs.next()) {
	          	Double tutar= rs.getDouble("Tutar");
	           	int vade= rs.getInt("Vade");
	          	lblvade.setText(String.valueOf(vade));
	          	lbltutar.setText(String.valueOf(tutar));
	          	
			         
	          } connection.close();
	         
	      } catch (SQLException sqlException) {
	          sqlException.printStackTrace();
	      }
        
				
    }//GEN-LAST:event_ad2ActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
      	try {
				Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			          PreparedStatement st = (PreparedStatement) connection
			              .prepareStatement("Select *from musteriler where AdSoyad = ? and TemsilciId=?");
			          st.setString(1, String.valueOf(ad.getSelectedItem()));
			          st.setInt(2, this.temsilci_id);
			          ResultSet rs = st.executeQuery();
			          while (rs.next()) {
			        	 hesapad.removeAllItems();
			          	//String hesaplar = rs.getString("HesapAd");
			          	int musteri_id = rs.getInt("MusteriId");
			         
			          	 PreparedStatement st2 = (PreparedStatement) connection
					              .prepareStatement("Select *from hesaplar where MusteriId = ? and HesapOnay=0");
			          	 	  st2.setString(1, String.valueOf(musteri_id));
					          ResultSet rs2 = st2.executeQuery();
					          while (rs2.next()) {
					          	String h_ad = rs2.getString("HesapAd");
					          	hesapad.addItem(h_ad);
					          	
					        
					          }
					        
			          } connection.close();
			         
			      } catch (SQLException sqlException) {
			          sqlException.printStackTrace();
			      }
        
       
		
					
    }//GEN-LAST:event_adActionPerformed

    private void hesapadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapadActionPerformed
      
    }//GEN-LAST:event_hesapadActionPerformed

    private void hesapad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapad2ActionPerformed
      try {
					
				 Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
			          PreparedStatement st = (PreparedStatement) connection
			              .prepareStatement("select *from kredi_talep k inner join hesaplar h ON h.HesapId=k.HesapId where k.KrediOnay=0 and h.HesapId in(select HesapId from hesaplar h inner join musteriler m ON m.MusteriId=h.MusteriId where m.AdSoyad=? and h.HesapAd=? )");
			          st.setString(1, String.valueOf(ad2.getSelectedItem()));
			          st.setString(2, String.valueOf(hesapad2.getSelectedItem()));
			          ResultSet rs = st.executeQuery();
			          while (rs.next()) {
			          	Double tutar= rs.getDouble("Tutar");
			           	int vade= rs.getInt("Vade");
			          	lblvade.setText(String.valueOf(vade));
			          	lbltutar.setText(String.valueOf(tutar));
			          	
					         
			          } connection.close();
			         
			      } catch (SQLException sqlException) {
			          sqlException.printStackTrace();
			      }
    }//GEN-LAST:event_hesapad2ActionPerformed

    private void GenelDurumFunc(boolean hesap_onaylandi_mi){
        if(hesap_onaylandi_mi==true){
            try{
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankasistemi", "root", "123");
	
             PreparedStatement stm = connection.prepareStatement("select HesapId from hesaplar where HesapAd=? and MusteriId = (select MusteriId from musteriler where AdSoyad=?)");
            stm.setString(1, String.valueOf(hesapad.getSelectedItem()));
            stm.setString(2, String.valueOf(ad.getSelectedItem()));
            ResultSet rst=stm.executeQuery();
             if(rst.next()){
               int hesapid=rst.getInt("HesapId");
               System.out.println(hesapid);
               String query="insert into geneldurum (Gelir,Gider,HesapId,bakiye) values('0','0','"+hesapid+"','0')";
                java.sql.Statement sta = connection.createStatement();
                int x = sta.executeUpdate(query);
                
                                                   
			               
          }
             connection.close();
              JOptionPane.showMessageDialog(null, "Onaylandı");
                setVisible(false);
                new Talepler(this.temsilci_id).setVisible(true);
     }catch (Exception exception) {
     exception.printStackTrace();
     }
        }else{
            JOptionPane.showMessageDialog(null, "hata");
            dispose();
            new Talepler(this.temsilci_id).setVisible(true);
	                    
        }
            
 
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Talepler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Talepler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Talepler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Talepler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Talepler().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ad;
    private javax.swing.JComboBox<String> ad2;
    private javax.swing.JToggleButton hesapOnay;
    private javax.swing.JComboBox<String> hesapad;
    private javax.swing.JComboBox<String> hesapad2;
    private javax.swing.JToggleButton iptal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton kredionay;
    private java.awt.Label lbltutar;
    private java.awt.Label lblvade;
    private javax.swing.JPanel talepler;
    // End of variables declaration//GEN-END:variables
}
